apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-agent-config
  namespace: wazuh
data:
  install.sh: |
    #/bin/bash

    # append this line so that wazuh-agentd will be able to recognize the auth service
    grep -qxF 'your-domain.com wazuh.wazuh.svc.cluster.local' /etc/hosts || echo 'your-domain.com wazuh.wazuh.svc.cluster.local' >> /etc/hosts

    WAZUH_MANAGER='your-domain.com' WAZUH_REGISTRATION_PASSWORD='password' WAZUH_AGENT_GROUP='default' yum install -y https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.9-1.x86_64.rpm

    echo "copying ossec files"
    cp /var/ossec.conf /var/authd.pass /var/ossec/etc/

    systemctl daemon-reload
    systemctl enable wazuh-agent
    systemctl start wazuh-agent
    systemctl -l status wazuh-agent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      job: wazuh-agent
  template:
    metadata:
      labels:
        job: wazuh-agent
    spec:
      hostPID: true
      hostIPC: true
      restartPolicy: Always
      containers:
      - image: rexlow/wazuh-agent:latest
        imagePullPolicy: Always
        name: wazuh-agent
        securityContext:
          privileged: true
        volumeMounts:
        - name: install-script
          mountPath: /tmp
        - name: host-mount
          mountPath: /host
        - mountPath: /var/run
          name: var-run
        - mountPath: /host/dev
          name: dev
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/etc
          name: etc
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /host/var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /host/boot
          name: boot
          readOnly: true
        - mountPath: /host/usr
          name: usr
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules
          readOnly: true
        - mountPath: /host/var/log
          name: log
          readOnly: true
      volumes:
      - name: install-script
        configMap:
          name: wazuh-agent-config
      - name: host-mount
        hostPath:
          path: /var
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: var-run
        hostPath:
          path: /var/run
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: etc
        hostPath:
          path: /etc
      - name: boot
        hostPath:
          path: /boot
      - name: usr
        hostPath:
          path: /usr
      - name: modules
        hostPath:
          path: /lib/modules
      - name: log
        hostPath:
          path: /var/log